package com.zp.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FcDsBizOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public FcDsBizOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTaskNoIsNull() {
            addCriterion("task_no is null");
            return (Criteria) this;
        }

        public Criteria andTaskNoIsNotNull() {
            addCriterion("task_no is not null");
            return (Criteria) this;
        }

        public Criteria andTaskNoEqualTo(Long value) {
            addCriterion("task_no =", value, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoNotEqualTo(Long value) {
            addCriterion("task_no <>", value, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoGreaterThan(Long value) {
            addCriterion("task_no >", value, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoGreaterThanOrEqualTo(Long value) {
            addCriterion("task_no >=", value, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoLessThan(Long value) {
            addCriterion("task_no <", value, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoLessThanOrEqualTo(Long value) {
            addCriterion("task_no <=", value, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoIn(List<Long> values) {
            addCriterion("task_no in", values, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoNotIn(List<Long> values) {
            addCriterion("task_no not in", values, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoBetween(Long value1, Long value2) {
            addCriterion("task_no between", value1, value2, "taskNo");
            return (Criteria) this;
        }

        public Criteria andTaskNoNotBetween(Long value1, Long value2) {
            addCriterion("task_no not between", value1, value2, "taskNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoIsNull() {
            addCriterion("request_no is null");
            return (Criteria) this;
        }

        public Criteria andRequestNoIsNotNull() {
            addCriterion("request_no is not null");
            return (Criteria) this;
        }

        public Criteria andRequestNoEqualTo(String value) {
            addCriterion("request_no =", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoNotEqualTo(String value) {
            addCriterion("request_no <>", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoGreaterThan(String value) {
            addCriterion("request_no >", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoGreaterThanOrEqualTo(String value) {
            addCriterion("request_no >=", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoLessThan(String value) {
            addCriterion("request_no <", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoLessThanOrEqualTo(String value) {
            addCriterion("request_no <=", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoLike(String value) {
            addCriterion("request_no like", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoNotLike(String value) {
            addCriterion("request_no not like", value, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoIn(List<String> values) {
            addCriterion("request_no in", values, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoNotIn(List<String> values) {
            addCriterion("request_no not in", values, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoBetween(String value1, String value2) {
            addCriterion("request_no between", value1, value2, "requestNo");
            return (Criteria) this;
        }

        public Criteria andRequestNoNotBetween(String value1, String value2) {
            addCriterion("request_no not between", value1, value2, "requestNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoIsNull() {
            addCriterion("biz_order_no is null");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoIsNotNull() {
            addCriterion("biz_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoEqualTo(String value) {
            addCriterion("biz_order_no =", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoNotEqualTo(String value) {
            addCriterion("biz_order_no <>", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoGreaterThan(String value) {
            addCriterion("biz_order_no >", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("biz_order_no >=", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoLessThan(String value) {
            addCriterion("biz_order_no <", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoLessThanOrEqualTo(String value) {
            addCriterion("biz_order_no <=", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoLike(String value) {
            addCriterion("biz_order_no like", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoNotLike(String value) {
            addCriterion("biz_order_no not like", value, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoIn(List<String> values) {
            addCriterion("biz_order_no in", values, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoNotIn(List<String> values) {
            addCriterion("biz_order_no not in", values, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoBetween(String value1, String value2) {
            addCriterion("biz_order_no between", value1, value2, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andBizOrderNoNotBetween(String value1, String value2) {
            addCriterion("biz_order_no not between", value1, value2, "bizOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoIsNull() {
            addCriterion("pay_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoIsNotNull() {
            addCriterion("pay_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoEqualTo(Long value) {
            addCriterion("pay_trade_no =", value, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoNotEqualTo(Long value) {
            addCriterion("pay_trade_no <>", value, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoGreaterThan(Long value) {
            addCriterion("pay_trade_no >", value, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_trade_no >=", value, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoLessThan(Long value) {
            addCriterion("pay_trade_no <", value, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoLessThanOrEqualTo(Long value) {
            addCriterion("pay_trade_no <=", value, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoIn(List<Long> values) {
            addCriterion("pay_trade_no in", values, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoNotIn(List<Long> values) {
            addCriterion("pay_trade_no not in", values, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoBetween(Long value1, Long value2) {
            addCriterion("pay_trade_no between", value1, value2, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andPayTradeNoNotBetween(Long value1, Long value2) {
            addCriterion("pay_trade_no not between", value1, value2, "payTradeNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoIsNull() {
            addCriterion("org_request_no is null");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoIsNotNull() {
            addCriterion("org_request_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoEqualTo(String value) {
            addCriterion("org_request_no =", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoNotEqualTo(String value) {
            addCriterion("org_request_no <>", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoGreaterThan(String value) {
            addCriterion("org_request_no >", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoGreaterThanOrEqualTo(String value) {
            addCriterion("org_request_no >=", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoLessThan(String value) {
            addCriterion("org_request_no <", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoLessThanOrEqualTo(String value) {
            addCriterion("org_request_no <=", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoLike(String value) {
            addCriterion("org_request_no like", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoNotLike(String value) {
            addCriterion("org_request_no not like", value, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoIn(List<String> values) {
            addCriterion("org_request_no in", values, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoNotIn(List<String> values) {
            addCriterion("org_request_no not in", values, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoBetween(String value1, String value2) {
            addCriterion("org_request_no between", value1, value2, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andOrgRequestNoNotBetween(String value1, String value2) {
            addCriterion("org_request_no not between", value1, value2, "orgRequestNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoIsNull() {
            addCriterion("parent_biz_order_no is null");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoIsNotNull() {
            addCriterion("parent_biz_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoEqualTo(String value) {
            addCriterion("parent_biz_order_no =", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoNotEqualTo(String value) {
            addCriterion("parent_biz_order_no <>", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoGreaterThan(String value) {
            addCriterion("parent_biz_order_no >", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("parent_biz_order_no >=", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoLessThan(String value) {
            addCriterion("parent_biz_order_no <", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoLessThanOrEqualTo(String value) {
            addCriterion("parent_biz_order_no <=", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoLike(String value) {
            addCriterion("parent_biz_order_no like", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoNotLike(String value) {
            addCriterion("parent_biz_order_no not like", value, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoIn(List<String> values) {
            addCriterion("parent_biz_order_no in", values, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoNotIn(List<String> values) {
            addCriterion("parent_biz_order_no not in", values, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoBetween(String value1, String value2) {
            addCriterion("parent_biz_order_no between", value1, value2, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andParentBizOrderNoNotBetween(String value1, String value2) {
            addCriterion("parent_biz_order_no not between", value1, value2, "parentBizOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayPeriodIsNull() {
            addCriterion("pay_period is null");
            return (Criteria) this;
        }

        public Criteria andPayPeriodIsNotNull() {
            addCriterion("pay_period is not null");
            return (Criteria) this;
        }

        public Criteria andPayPeriodEqualTo(Byte value) {
            addCriterion("pay_period =", value, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodNotEqualTo(Byte value) {
            addCriterion("pay_period <>", value, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodGreaterThan(Byte value) {
            addCriterion("pay_period >", value, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodGreaterThanOrEqualTo(Byte value) {
            addCriterion("pay_period >=", value, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodLessThan(Byte value) {
            addCriterion("pay_period <", value, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodLessThanOrEqualTo(Byte value) {
            addCriterion("pay_period <=", value, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodIn(List<Byte> values) {
            addCriterion("pay_period in", values, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodNotIn(List<Byte> values) {
            addCriterion("pay_period not in", values, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodBetween(Byte value1, Byte value2) {
            addCriterion("pay_period between", value1, value2, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andPayPeriodNotBetween(Byte value1, Byte value2) {
            addCriterion("pay_period not between", value1, value2, "payPeriod");
            return (Criteria) this;
        }

        public Criteria andAccessCodeIsNull() {
            addCriterion("access_code is null");
            return (Criteria) this;
        }

        public Criteria andAccessCodeIsNotNull() {
            addCriterion("access_code is not null");
            return (Criteria) this;
        }

        public Criteria andAccessCodeEqualTo(String value) {
            addCriterion("access_code =", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotEqualTo(String value) {
            addCriterion("access_code <>", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeGreaterThan(String value) {
            addCriterion("access_code >", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("access_code >=", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeLessThan(String value) {
            addCriterion("access_code <", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeLessThanOrEqualTo(String value) {
            addCriterion("access_code <=", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeLike(String value) {
            addCriterion("access_code like", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotLike(String value) {
            addCriterion("access_code not like", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeIn(List<String> values) {
            addCriterion("access_code in", values, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotIn(List<String> values) {
            addCriterion("access_code not in", values, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeBetween(String value1, String value2) {
            addCriterion("access_code between", value1, value2, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotBetween(String value1, String value2) {
            addCriterion("access_code not between", value1, value2, "accessCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeIsNull() {
            addCriterion("biz_code is null");
            return (Criteria) this;
        }

        public Criteria andBizCodeIsNotNull() {
            addCriterion("biz_code is not null");
            return (Criteria) this;
        }

        public Criteria andBizCodeEqualTo(String value) {
            addCriterion("biz_code =", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeNotEqualTo(String value) {
            addCriterion("biz_code <>", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeGreaterThan(String value) {
            addCriterion("biz_code >", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeGreaterThanOrEqualTo(String value) {
            addCriterion("biz_code >=", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeLessThan(String value) {
            addCriterion("biz_code <", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeLessThanOrEqualTo(String value) {
            addCriterion("biz_code <=", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeLike(String value) {
            addCriterion("biz_code like", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeNotLike(String value) {
            addCriterion("biz_code not like", value, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeIn(List<String> values) {
            addCriterion("biz_code in", values, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeNotIn(List<String> values) {
            addCriterion("biz_code not in", values, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeBetween(String value1, String value2) {
            addCriterion("biz_code between", value1, value2, "bizCode");
            return (Criteria) this;
        }

        public Criteria andBizCodeNotBetween(String value1, String value2) {
            addCriterion("biz_code not between", value1, value2, "bizCode");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameIsNull() {
            addCriterion("notruck_company_name is null");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameIsNotNull() {
            addCriterion("notruck_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameEqualTo(String value) {
            addCriterion("notruck_company_name =", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameNotEqualTo(String value) {
            addCriterion("notruck_company_name <>", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameGreaterThan(String value) {
            addCriterion("notruck_company_name >", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("notruck_company_name >=", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameLessThan(String value) {
            addCriterion("notruck_company_name <", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("notruck_company_name <=", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameLike(String value) {
            addCriterion("notruck_company_name like", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameNotLike(String value) {
            addCriterion("notruck_company_name not like", value, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameIn(List<String> values) {
            addCriterion("notruck_company_name in", values, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameNotIn(List<String> values) {
            addCriterion("notruck_company_name not in", values, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameBetween(String value1, String value2) {
            addCriterion("notruck_company_name between", value1, value2, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyNameNotBetween(String value1, String value2) {
            addCriterion("notruck_company_name not between", value1, value2, "notruckCompanyName");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdIsNull() {
            addCriterion("notruck_company_id is null");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdIsNotNull() {
            addCriterion("notruck_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdEqualTo(String value) {
            addCriterion("notruck_company_id =", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdNotEqualTo(String value) {
            addCriterion("notruck_company_id <>", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdGreaterThan(String value) {
            addCriterion("notruck_company_id >", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("notruck_company_id >=", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdLessThan(String value) {
            addCriterion("notruck_company_id <", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("notruck_company_id <=", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdLike(String value) {
            addCriterion("notruck_company_id like", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdNotLike(String value) {
            addCriterion("notruck_company_id not like", value, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdIn(List<String> values) {
            addCriterion("notruck_company_id in", values, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdNotIn(List<String> values) {
            addCriterion("notruck_company_id not in", values, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdBetween(String value1, String value2) {
            addCriterion("notruck_company_id between", value1, value2, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andNotruckCompanyIdNotBetween(String value1, String value2) {
            addCriterion("notruck_company_id not between", value1, value2, "notruckCompanyId");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNull() {
            addCriterion("trade_type is null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNotNull() {
            addCriterion("trade_type is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeEqualTo(Byte value) {
            addCriterion("trade_type =", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotEqualTo(Byte value) {
            addCriterion("trade_type <>", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThan(Byte value) {
            addCriterion("trade_type >", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("trade_type >=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThan(Byte value) {
            addCriterion("trade_type <", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThanOrEqualTo(Byte value) {
            addCriterion("trade_type <=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIn(List<Byte> values) {
            addCriterion("trade_type in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotIn(List<Byte> values) {
            addCriterion("trade_type not in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeBetween(Byte value1, Byte value2) {
            addCriterion("trade_type between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("trade_type not between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andActionCodeIsNull() {
            addCriterion("action_code is null");
            return (Criteria) this;
        }

        public Criteria andActionCodeIsNotNull() {
            addCriterion("action_code is not null");
            return (Criteria) this;
        }

        public Criteria andActionCodeEqualTo(Integer value) {
            addCriterion("action_code =", value, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeNotEqualTo(Integer value) {
            addCriterion("action_code <>", value, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeGreaterThan(Integer value) {
            addCriterion("action_code >", value, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("action_code >=", value, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeLessThan(Integer value) {
            addCriterion("action_code <", value, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeLessThanOrEqualTo(Integer value) {
            addCriterion("action_code <=", value, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeIn(List<Integer> values) {
            addCriterion("action_code in", values, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeNotIn(List<Integer> values) {
            addCriterion("action_code not in", values, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeBetween(Integer value1, Integer value2) {
            addCriterion("action_code between", value1, value2, "actionCode");
            return (Criteria) this;
        }

        public Criteria andActionCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("action_code not between", value1, value2, "actionCode");
            return (Criteria) this;
        }

        public Criteria andPayMethodIsNull() {
            addCriterion("pay_method is null");
            return (Criteria) this;
        }

        public Criteria andPayMethodIsNotNull() {
            addCriterion("pay_method is not null");
            return (Criteria) this;
        }

        public Criteria andPayMethodEqualTo(String value) {
            addCriterion("pay_method =", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodNotEqualTo(String value) {
            addCriterion("pay_method <>", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodGreaterThan(String value) {
            addCriterion("pay_method >", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodGreaterThanOrEqualTo(String value) {
            addCriterion("pay_method >=", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodLessThan(String value) {
            addCriterion("pay_method <", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodLessThanOrEqualTo(String value) {
            addCriterion("pay_method <=", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodLike(String value) {
            addCriterion("pay_method like", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodNotLike(String value) {
            addCriterion("pay_method not like", value, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodIn(List<String> values) {
            addCriterion("pay_method in", values, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodNotIn(List<String> values) {
            addCriterion("pay_method not in", values, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodBetween(String value1, String value2) {
            addCriterion("pay_method between", value1, value2, "payMethod");
            return (Criteria) this;
        }

        public Criteria andPayMethodNotBetween(String value1, String value2) {
            addCriterion("pay_method not between", value1, value2, "payMethod");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNull() {
            addCriterion("order_amount is null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIsNotNull() {
            addCriterion("order_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAmountEqualTo(Long value) {
            addCriterion("order_amount =", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotEqualTo(Long value) {
            addCriterion("order_amount <>", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThan(Long value) {
            addCriterion("order_amount >", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("order_amount >=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThan(Long value) {
            addCriterion("order_amount <", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountLessThanOrEqualTo(Long value) {
            addCriterion("order_amount <=", value, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountIn(List<Long> values) {
            addCriterion("order_amount in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotIn(List<Long> values) {
            addCriterion("order_amount not in", values, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountBetween(Long value1, Long value2) {
            addCriterion("order_amount between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andOrderAmountNotBetween(Long value1, Long value2) {
            addCriterion("order_amount not between", value1, value2, "orderAmount");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsIsNull() {
            addCriterion("marketing_details is null");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsIsNotNull() {
            addCriterion("marketing_details is not null");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsEqualTo(String value) {
            addCriterion("marketing_details =", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsNotEqualTo(String value) {
            addCriterion("marketing_details <>", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsGreaterThan(String value) {
            addCriterion("marketing_details >", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsGreaterThanOrEqualTo(String value) {
            addCriterion("marketing_details >=", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsLessThan(String value) {
            addCriterion("marketing_details <", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsLessThanOrEqualTo(String value) {
            addCriterion("marketing_details <=", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsLike(String value) {
            addCriterion("marketing_details like", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsNotLike(String value) {
            addCriterion("marketing_details not like", value, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsIn(List<String> values) {
            addCriterion("marketing_details in", values, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsNotIn(List<String> values) {
            addCriterion("marketing_details not in", values, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsBetween(String value1, String value2) {
            addCriterion("marketing_details between", value1, value2, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andMarketingDetailsNotBetween(String value1, String value2) {
            addCriterion("marketing_details not between", value1, value2, "marketingDetails");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIsNull() {
            addCriterion("finish_time is null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIsNotNull() {
            addCriterion("finish_time is not null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeEqualTo(Date value) {
            addCriterion("finish_time =", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotEqualTo(Date value) {
            addCriterion("finish_time <>", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeGreaterThan(Date value) {
            addCriterion("finish_time >", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("finish_time >=", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeLessThan(Date value) {
            addCriterion("finish_time <", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeLessThanOrEqualTo(Date value) {
            addCriterion("finish_time <=", value, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeIn(List<Date> values) {
            addCriterion("finish_time in", values, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotIn(List<Date> values) {
            addCriterion("finish_time not in", values, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeBetween(Date value1, Date value2) {
            addCriterion("finish_time between", value1, value2, "finishTime");
            return (Criteria) this;
        }

        public Criteria andFinishTimeNotBetween(Date value1, Date value2) {
            addCriterion("finish_time not between", value1, value2, "finishTime");
            return (Criteria) this;
        }

        public Criteria andPayerUidIsNull() {
            addCriterion("payer_uid is null");
            return (Criteria) this;
        }

        public Criteria andPayerUidIsNotNull() {
            addCriterion("payer_uid is not null");
            return (Criteria) this;
        }

        public Criteria andPayerUidEqualTo(String value) {
            addCriterion("payer_uid =", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidNotEqualTo(String value) {
            addCriterion("payer_uid <>", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidGreaterThan(String value) {
            addCriterion("payer_uid >", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidGreaterThanOrEqualTo(String value) {
            addCriterion("payer_uid >=", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidLessThan(String value) {
            addCriterion("payer_uid <", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidLessThanOrEqualTo(String value) {
            addCriterion("payer_uid <=", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidLike(String value) {
            addCriterion("payer_uid like", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidNotLike(String value) {
            addCriterion("payer_uid not like", value, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidIn(List<String> values) {
            addCriterion("payer_uid in", values, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidNotIn(List<String> values) {
            addCriterion("payer_uid not in", values, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidBetween(String value1, String value2) {
            addCriterion("payer_uid between", value1, value2, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayerUidNotBetween(String value1, String value2) {
            addCriterion("payer_uid not between", value1, value2, "payerUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIsNull() {
            addCriterion("payee_uid is null");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIsNotNull() {
            addCriterion("payee_uid is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeUidEqualTo(String value) {
            addCriterion("payee_uid =", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotEqualTo(String value) {
            addCriterion("payee_uid <>", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidGreaterThan(String value) {
            addCriterion("payee_uid >", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidGreaterThanOrEqualTo(String value) {
            addCriterion("payee_uid >=", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidLessThan(String value) {
            addCriterion("payee_uid <", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidLessThanOrEqualTo(String value) {
            addCriterion("payee_uid <=", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidLike(String value) {
            addCriterion("payee_uid like", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotLike(String value) {
            addCriterion("payee_uid not like", value, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidIn(List<String> values) {
            addCriterion("payee_uid in", values, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotIn(List<String> values) {
            addCriterion("payee_uid not in", values, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidBetween(String value1, String value2) {
            addCriterion("payee_uid between", value1, value2, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andPayeeUidNotBetween(String value1, String value2) {
            addCriterion("payee_uid not between", value1, value2, "payeeUid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 06 12:07:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fc_ds_biz_order
     *
     * @mbg.generated Fri Mar 06 12:07:21 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}