package com.zp.dao.entity;

import java.util.Date;

public class FcDsBizOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.id
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.task_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Long taskNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.request_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String requestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.biz_order_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String bizOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.pay_trade_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Long payTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.org_request_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String orgRequestNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.parent_biz_order_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String parentBizOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.pay_period
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Byte payPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.access_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String accessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.biz_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String bizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.notruck_company_name
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String notruckCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.notruck_company_id
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String notruckCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.trade_type
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Byte tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.action_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Integer actionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.pay_method
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String payMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.order_amount
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Long orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.marketing_details
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String marketingDetails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.create_time
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.finish_time
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.payer_uid
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String payerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.payee_uid
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String payeeUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.status
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fc_ds_biz_order_detail.royalty_details
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    private String royaltyDetails;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.id
     *
     * @return the value of fc_ds_biz_order_detail.id
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.id
     *
     * @param id the value for fc_ds_biz_order_detail.id
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.task_no
     *
     * @return the value of fc_ds_biz_order_detail.task_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Long getTaskNo() {
        return taskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.task_no
     *
     * @param taskNo the value for fc_ds_biz_order_detail.task_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setTaskNo(Long taskNo) {
        this.taskNo = taskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.request_no
     *
     * @return the value of fc_ds_biz_order_detail.request_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getRequestNo() {
        return requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.request_no
     *
     * @param requestNo the value for fc_ds_biz_order_detail.request_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo == null ? null : requestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.biz_order_no
     *
     * @return the value of fc_ds_biz_order_detail.biz_order_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getBizOrderNo() {
        return bizOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.biz_order_no
     *
     * @param bizOrderNo the value for fc_ds_biz_order_detail.biz_order_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setBizOrderNo(String bizOrderNo) {
        this.bizOrderNo = bizOrderNo == null ? null : bizOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.pay_trade_no
     *
     * @return the value of fc_ds_biz_order_detail.pay_trade_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Long getPayTradeNo() {
        return payTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.pay_trade_no
     *
     * @param payTradeNo the value for fc_ds_biz_order_detail.pay_trade_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setPayTradeNo(Long payTradeNo) {
        this.payTradeNo = payTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.org_request_no
     *
     * @return the value of fc_ds_biz_order_detail.org_request_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getOrgRequestNo() {
        return orgRequestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.org_request_no
     *
     * @param orgRequestNo the value for fc_ds_biz_order_detail.org_request_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setOrgRequestNo(String orgRequestNo) {
        this.orgRequestNo = orgRequestNo == null ? null : orgRequestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.parent_biz_order_no
     *
     * @return the value of fc_ds_biz_order_detail.parent_biz_order_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getParentBizOrderNo() {
        return parentBizOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.parent_biz_order_no
     *
     * @param parentBizOrderNo the value for fc_ds_biz_order_detail.parent_biz_order_no
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setParentBizOrderNo(String parentBizOrderNo) {
        this.parentBizOrderNo = parentBizOrderNo == null ? null : parentBizOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.pay_period
     *
     * @return the value of fc_ds_biz_order_detail.pay_period
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Byte getPayPeriod() {
        return payPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.pay_period
     *
     * @param payPeriod the value for fc_ds_biz_order_detail.pay_period
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setPayPeriod(Byte payPeriod) {
        this.payPeriod = payPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.access_code
     *
     * @return the value of fc_ds_biz_order_detail.access_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getAccessCode() {
        return accessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.access_code
     *
     * @param accessCode the value for fc_ds_biz_order_detail.access_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode == null ? null : accessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.biz_code
     *
     * @return the value of fc_ds_biz_order_detail.biz_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.biz_code
     *
     * @param bizCode the value for fc_ds_biz_order_detail.biz_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.notruck_company_name
     *
     * @return the value of fc_ds_biz_order_detail.notruck_company_name
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getNotruckCompanyName() {
        return notruckCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.notruck_company_name
     *
     * @param notruckCompanyName the value for fc_ds_biz_order_detail.notruck_company_name
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setNotruckCompanyName(String notruckCompanyName) {
        this.notruckCompanyName = notruckCompanyName == null ? null : notruckCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.notruck_company_id
     *
     * @return the value of fc_ds_biz_order_detail.notruck_company_id
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getNotruckCompanyId() {
        return notruckCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.notruck_company_id
     *
     * @param notruckCompanyId the value for fc_ds_biz_order_detail.notruck_company_id
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setNotruckCompanyId(String notruckCompanyId) {
        this.notruckCompanyId = notruckCompanyId == null ? null : notruckCompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.trade_type
     *
     * @return the value of fc_ds_biz_order_detail.trade_type
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Byte getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.trade_type
     *
     * @param tradeType the value for fc_ds_biz_order_detail.trade_type
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setTradeType(Byte tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.action_code
     *
     * @return the value of fc_ds_biz_order_detail.action_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Integer getActionCode() {
        return actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.action_code
     *
     * @param actionCode the value for fc_ds_biz_order_detail.action_code
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setActionCode(Integer actionCode) {
        this.actionCode = actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.pay_method
     *
     * @return the value of fc_ds_biz_order_detail.pay_method
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.pay_method
     *
     * @param payMethod the value for fc_ds_biz_order_detail.pay_method
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod == null ? null : payMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.order_amount
     *
     * @return the value of fc_ds_biz_order_detail.order_amount
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Long getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.order_amount
     *
     * @param orderAmount the value for fc_ds_biz_order_detail.order_amount
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.marketing_details
     *
     * @return the value of fc_ds_biz_order_detail.marketing_details
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getMarketingDetails() {
        return marketingDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.marketing_details
     *
     * @param marketingDetails the value for fc_ds_biz_order_detail.marketing_details
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setMarketingDetails(String marketingDetails) {
        this.marketingDetails = marketingDetails == null ? null : marketingDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.create_time
     *
     * @return the value of fc_ds_biz_order_detail.create_time
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.create_time
     *
     * @param createTime the value for fc_ds_biz_order_detail.create_time
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.finish_time
     *
     * @return the value of fc_ds_biz_order_detail.finish_time
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.finish_time
     *
     * @param finishTime the value for fc_ds_biz_order_detail.finish_time
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.payer_uid
     *
     * @return the value of fc_ds_biz_order_detail.payer_uid
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getPayerUid() {
        return payerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.payer_uid
     *
     * @param payerUid the value for fc_ds_biz_order_detail.payer_uid
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setPayerUid(String payerUid) {
        this.payerUid = payerUid == null ? null : payerUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.payee_uid
     *
     * @return the value of fc_ds_biz_order_detail.payee_uid
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getPayeeUid() {
        return payeeUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.payee_uid
     *
     * @param payeeUid the value for fc_ds_biz_order_detail.payee_uid
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setPayeeUid(String payeeUid) {
        this.payeeUid = payeeUid == null ? null : payeeUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.status
     *
     * @return the value of fc_ds_biz_order_detail.status
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.status
     *
     * @param status the value for fc_ds_biz_order_detail.status
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fc_ds_biz_order_detail.royalty_details
     *
     * @return the value of fc_ds_biz_order_detail.royalty_details
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public String getRoyaltyDetails() {
        return royaltyDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fc_ds_biz_order_detail.royalty_details
     *
     * @param royaltyDetails the value for fc_ds_biz_order_detail.royalty_details
     *
     * @mbg.generated Sat Mar 07 18:27:09 CST 2020
     */
    public void setRoyaltyDetails(String royaltyDetails) {
        this.royaltyDetails = royaltyDetails == null ? null : royaltyDetails.trim();
    }
}